alias cdtemp='cd $(mktemp -d)'
alias fzff='fzf --preview="cat {}"'
alias ll='exa -al'
alias mkdir='mkdir -pv'
alias reload='source ~/.zshrc'
alias rm='rm -i'
alias python='python3'
alias obsidian='flatpak run md.obsidian.Obsidian'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git pull'
alias gs='git status -s'
